### PR TITLE
Negative photometry

### PR DESCRIPTION
**Pull request by dmitryduev**
Moved @dannygoldstein's code to the new `alert_broker_ztf.py` script.

### CODE REVIEW

**Comment by dannygoldstein** [comment]
Lot of diffs. I think this is merging into master instead of my PR branch?

**Comment by dmitryduev** [comment]
Once you merge this in, the diff wrt master should be down to one file.

**Comment by dmitryduev** [comment]
At least that was the idea :)

**Comment by dannygoldstein** [comment]
My PR is not on dannygoldstein:master -- it's on dannygoldstein:negative_phot -- please open a PR against that branch

**Comment by dmitryduev** [comment]
Dammit, sorry about that. Changed the base branch.

**Comment by dmitryduev** [comment]
Closing in favor of #2.

**Pull request closed without merging**
